### ISSUE TITLE
Ethernet Connection

### ISSUE THREAD

**Issue by schotime** [neerolyte/selpi#10]
I see you have the ability to use TCP to connect also. Is this directly to the unit or through the Ethernet Adaptor Lead?

**Comment by neerolyte** [comment]
I've only used it so far by starting [selpi itself in proxy mode](https://github.com/neerolyte/selpi#proxy) with some kind of direct connection. SP Pros don't have an ethernet port or AFAIK an IP stack and thus no way to talk TCP directly.

A serial to ethernet adapter _should_ work, but I haven't tested it.
