### ISSUE TITLE
Is the Response Data Big Endian?

### ISSUE THREAD

**Issue by schotime** [neerolyte/selpi#11]
I was looking through the SP-link code and also some other Java code and both seem to convert the response bytes from Big Endian but I noticed that no such conversion was done in this library? 
Do you know anything of this? 
I'm assuming you would've known if the values weren't correct.

**Comment by neerolyte** [comment]
The struct module does it based on whether the first character of the format is `<` or `>`, see - https://docs.python.org/3/library/struct.html#byte-order-size-and-alignment .

The struct format strings are defined at https://github.com/neerolyte/selpi/blob/7ab1f60da206716b71c34d39593a086a7f024d79/memory/variable.py#L152-L169 and consumed at https://github.com/neerolyte/selpi/blob/7ab1f60da206716b71c34d39593a086a7f024d79/memory/variable.py#L211-L212 .

The structure would allow for the remote data to be mixed endians, but I think it's all little endian.

**Comment by schotime** [comment]
Yeh I got that, but its just weird that this method gets called for all data received in SP-Link

![image](https://user-images.githubusercontent.com/202923/150030472-0c96f7f8-5e73-4da7-89ab-5e1c23a8b3c1.png)

**Comment by schotime** [comment]
Of which i've just realised doesn't actually flip the bytes at all, and just converts from the bytes to ushorts in the order they came in.

**Comment by neerolyte** [comment]
Hey @schotime, I don't think I understand the question well enough. I think it's effectively the same conversion - just sizing from the array size and presumably signing somewhere else.

**Comment by neerolyte** [comment]
Sorry my page was way behind, posted my comment before I saw your second one.
